### ISSUE TITLE
BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP contains the same URL for two separate artifacts

### ISSUE THREAD

**Issue by WarrenFaith** [bitrise-steplib/steps-deploy-to-bitrise-io#104]
Stumbling about the issue reported as #59 I was able to fix the formatting of the url map (for a slack message), but in my case (I use the Android Build step to build an aab) the map contains an entry for the apk and for the aab. But both links are the same and show the apk install page.
Also the aab (when viewing the artifacts tab) has no public install/download page set but the apk has.

If I read the description for compressing flag correctly
> If this option is turned off, the artifacts found in the Deploy directory folder will be deployed separately.

a set to false should deploy them separately. That is the case but not all settings seem to be applied there.

Any idea what I might do wrong?

```
tag_store_test:
    steps:
    - android-build:
        inputs:
        - variant: rcRelease
        - build_type: aab
        - module: module
    - deploy-to-bitrise-io:
        inputs:
        - notify_email_list: "$EMAIL_TEAM_QA, $EMAIL_TEAM_ANDROID"
        - notify_user_groups: none
        - debug_mode: 'true'
        - deploy_path: "/bitrise/deploy/"
        - public_install_page_url_map_format: "{{range $index, $element := .}}{{if
            $index}} | {{end}}{{$element.File}} => {{$element.URL}}{{end}}"
        - zip_name: ''
        is_always_run: false
    - slack@3.1.3:
        inputs:
        - channel: "#android-notifications"
        - message: |-
            $BITRISE_GIT_TAG was build and can be downloaded here:
            APK: $BITRISE_PUBLIC_INSTALL_PAGE_URL
        - message_on_error: "$BITRISE_GIT_TAG failed to build. BuildLog: $BITRISE_BUILD_URL"
        - webhook_url: "$SLACK_WEBHOOK"
        - from_username: Android CI - OK
        - from_username_on_error: Android CI - ERROR
        - channel_on_error: "#android-notifications"
        - timestamp: 'no'
        - fields: "\n"
        - buttons: "\n"
        - footer: ''
        - footer_icon: ''
        - author_name: ''
        - pretext: ''
        - title: ''
        - image_url: "$BITRISE_PUBLIC_INSTALL_PAGE_QR_CODE_IMAGE_URL"
    before_run:
    - _preSetupVpn
    after_run:
    - _afterBuild
```

Log from this build step:

> +------------------------------------------------------------------------------+
> | (1) deploy-to-bitrise-io                                                     |
> +------------------------------------------------------------------------------+
> | id: deploy-to-bitrise-io                                                     |
> | version: 1.9.0                                                               |
> | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
> | toolkit: go                                                                  |
> | time: 2019-09-26T15:05:12Z                                                   |
> +------------------------------------------------------------------------------+
> |                                                                              |
> Config:
> - BuildURL: https://app.bitrise.io/build/e4b0[REDACTED]e7e24
> - APIToken: [REDACTED]
> - IsCompress: false
> - ZipName: 
> - DeployPath: /bitrise/deploy/[REDACTED]-rc-release.aab
> - NotifyUserGroups: none
> - NotifyEmailList: qa@[REDACTED].com
> - IsPublicPageEnabled: true
> - PublicInstallPageMapFormat: {{range $index, $element := .}}{{if $index}}|{{end}}{{$element.File}}=>{{$element.URL}}{{end}}
> - BuildSlug: e4b0[REDACTED]e7e24
> - TestDeployDir: /tmp/test_results208575171
> - AppSlug: 10e[REDACTED]9b90
> - AddonAPIBaseURL: [REDACTED]
> - AddonAPIToken: [REDACTED]
> - DebugMode: true
> Deploying single file
> List of files to deploy
> - /bitrise/deploy/[REDACTED]-rc-release.aab
> Deploying files
> Looking for universal APK pair for: /bitrise/deploy/[REDACTED]-rc-release.aab
> Does not have universal APK pair, generating...
> Generated universal APK pair: /tmp/aab-bundle825052974/[REDACTED]-rc-universal-release.apk
> Uploading apk file: /tmp/aab-bundle825052974/[REDACTED]-rc-universal-release.apk
> analyzing apk
>   apk infos: map[app_name:[REDACTED] RC min_sdk_version:21 package_name:[REDACTED].rc version_code:3348 version_name:test_1.2.3_store]
> creating artifact
>   file size: 34MB
> uploading artifact
> finishing artifact
> Uploading aab file: /bitrise/deploy/[REDACTED]-rc-release.aab
> - analyzing aab
> - fetching info
> $ java "-jar" "/tmp/tool062088885/bundletool-all-0.9.0.jar" "dump" "manifest" "--bundle" "/bitrise/deploy/[REDACTED]-rc-release.aab"
>   aab infos: map[package_name:10 version_code:3348 version_name:test_1.2.3_store]
> creating artifact
>   file size: 34MB
> uploading artifact
> finishing artifact
> Success
> You can find the Artifact on Bitrise, on the Build's page: https://app.bitrise.io/build/e4b0[REDACTED]7e24
> The public install page url is now available in the Environment Variable: BITRISE_PUBLIC_INSTALL_PAGE_URL (value: https://app.bitrise.io/artifact/22267062/p/e25......694db3)
> A map of deployed files and their public install page urls is now available in the Environment Variable: BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP (value: [REDACTED]-rc-universal-release.apk=>https://app.bitrise.io/artifact/22267062/p/e25......694db3|[REDACTED]-rc-release.aab=>https://app.bitrise.io/artifact/22267062/p/e25......694db3)

I also see some relation with #93
