### ISSUE TITLE
BITRISE_PUBLIC_INSTALL_PAGE_URL is not available for android builds

### ISSUE THREAD

**Issue by juancarlosqr** [bitrise-steplib/steps-deploy-to-bitrise-io#146]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.0.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? I don't have a local setup 

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

For **android only**, the `BITRISE_PUBLIC_INSTALL_PAGE_URL` is not available anymore with version 2, so I can't include it in the slack step buttons. Here is the step configuration I have:

```yml
- deploy-to-bitrise-io@2:
    outputs:
    - BITRISE_PUBLIC_INSTALL_PAGE_URL: ANDROID_INSTALL_PAGE
```

Then I'm using the `ANDROID_INSTALL_PAGE` var in the `slack` step:

```yml
    - slack@3:
        inputs:
        - channel: "#pelvina-daily-native-builds"
        - pretext: "*Build Succeeded (android)!*"
        - pretext_on_error: "*Build Failed (android)!*"
        - webhook_url: "$SLACK_WEBHOOK_URL"
        - buttons: |
            View App|${BITRISE_APP_URL}
            View Build|${BITRISE_BUILD_URL}
            Install Page|${ANDROID_INSTALL_PAGE}
```

But the var is empty:

```sh
- Buttons: View App|https://app.bitrise.io/app/36b901ba8ea828a1
View Build|https://app.bitrise.io/build/c4296084-1701-4e61-b0ba-4f29471997a2
Install Page|
```

If I use the same step configuration for same project with step's version `1.x.x`, it works and adds the install url to env vars. Maybe is due to a new configuration setting I need to set but was not able to find anything in the docs about it. Thanks in advanced for any provided guidance

### Bitrise info

- Build URL: https://app.bitrise.io/build/c4296084-1701-4e61-b0ba-4f29471997a2#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log:

<details>
  <pre>
Success
You can find the Artifact on Bitrise, on the Build's page: https://app.bitrise.io/build/c4296084-1701-4e61-b0ba-4f29471997a2
A map of deployed files and their permanent download urls is now available in the Environment Variable: BITRISE_PERMANENT_DOWNLOAD_URL_MAP (value: app-release-bitrise-signed.aab=>https://app.bitrise.io/artifact/a8852b9f49d10f3c/download|app-release.aab=>https://app.bitrise.io/artifact/ba8c41acea285db0/download)
  </pre>
</details>

### Steps to reproduce

1. Change step version to `2.x.x`
2. Trigger a new build for android
