### ISSUE TITLE
New Tar Upload Not Expanding As Expected

### ISSUE THREAD

**Issue by bassrock** [bitrise-steplib/steps-deploy-to-bitrise-io#162]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? Not setup to be able to try this

### Issue description

It looks like the switch to Tar is causing a folder to not expand as expected. https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/pull/161

Instead of a folder like `/var/folder/test` uploading and then expanding to `/var/folder/test` it is now expanding into `/var/folder/test/var/folder/test`

### Bitrise info

- Build URL: https://app.bitrise.io/build/e026e783-e266-461c-bfc8-6619baa23f0d
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_
- Log: 

<details>
  <pre>

Switching to workflow: run_tests_iphone_14
+------------------------------------------------------------------------------+
| (0) script@1                                                                 |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-10-19T20:56:24Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
total 0
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 .
0 drwx------  3 vagrant  staff  96 Oct 19 20:56 ..
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 var
/var/folders/gx/0jx30grn0xqb3pvktj4731840000gn/T/_artifact_pull1873648077/test_bundle1311517843
total 0
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 .
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 ..
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 folders
ls: /var/folders/gx/0jx30grn0xqb3pvktj4731840000gn/T/_artifact_pull1873648077/test_bundle1311517843/var/folders/gx/0jx30grn0xqb3pvktj4731840000gn/T/_artifact_pull1873648077/test_bundle1311517843: No such file or directory
|                              
  </pre>
</details>

### Steps to reproduce

1. Have a deploy to bitrise step like:
```
      - xcode-build-for-test:
          inputs:
            - destination: generic/platform=iOS Simulator
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_TEST_BUNDLE_PATH:BITRISE_TEST_BUNDLE_PATH'
```

Then another workflow like:

```
  run_tests_iphone_14:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: build-and-test.test_build
      - xcode-test-without-building:
          inputs:
            - xctestrun: '$BITRISE_TEST_BUNDLE_PATH/$TEST_BUNDLE_NAME'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_IPHONE_14_TEST_XCRESULT_PATH'
```
